In [1]:
#problem 1:

In [2]:
#Is gender independent of education level? A random sample of 395 people were
#surveyed and each person was asked to report the highest education level they
#obtained. The data that resulted from the survey is summarized in the following table:
#High School Bachelors Masters Ph.d. Total
#Female 60 54 46 41 201
#Male 40 44 53 57 194
#Total 100 98 99 98 395
#Question: Are gender and education level dependent at 5% level of significance? In
#other words, given the data collected above, is there a relationship between the gender
#of an individual and the level of education that they have obtained?

In [4]:
#Null hypothesis is H0: Education level and gender are independent
#Alternate hypothesis H1: Education level and gender are dependent

In [7]:
female = [60,54,46,41]
male = [40,44,53,57]

In [8]:
import numpy as np
from scipy import stats

In [9]:
total = np.array([female,male])

In [12]:
total

array([[60, 54, 46, 41],
       [40, 44, 53, 57]])

In [17]:
#performoing the chi-square test to determine whether the observed value of one variable
#depends on the observed value of a different variable
stats.chi2_contingency(total)

(8.006066246262538,
 0.045886500891747214,
 3,
 array([[50.88607595, 49.86835443, 50.37721519, 49.86835443],
        [49.11392405, 48.13164557, 48.62278481, 48.13164557]]))

In [14]:
chi2_stat, p_val, dof, ex = stats.chi2_contingency(total)
print("===Chi2 Stat===")
print(chi2_stat)
print("\n")
print("===Degrees of Freedom===")
print(dof)
print("\n")
print("===P-Value===")
print(p_val)
print("\n")
print("===Contingency Table===")
print(ex)

===Chi2 Stat===
8.006066246262538


===Degrees of Freedom===
3


===P-Value===
0.045886500891747214


===Contingency Table===
[[50.88607595 49.86835443 50.37721519 49.86835443]
 [49.11392405 48.13164557 48.62278481 48.13164557]]


In [15]:
#The critical value of χ2 with 3 degree of freedom is 7.815. Since 8.006 > 7.815, therefore we reject
#the null hypothesis and conclude that the education level depends on gender at a 5% level of
#significance

In [18]:
#Problem 2:

In [19]:
#Using the following data, perform a oneway analysis of variance using α=.05. Write up
#the results in APA format.

#[Group1: 51, 45, 33, 45, 67]
#[Group2: 23, 43, 23, 43, 45]
#[Group3: 56, 76, 74, 87, 56]

In [56]:
G1 = [51,45,33,45,67]
G2 = [23,43,23,43,45]
G3 = [56,76,74,87,56]

In [57]:
def sqdev(data):
    return([(data-np.mean(data))**2 for i in data][0])

In [59]:
g1= sqdev(G1)

In [60]:
g1

array([  7.84,  10.24, 231.04,  10.24, 353.44])

In [61]:
g2 = sqdev(G2)

In [62]:
g2

array([153.76,  57.76, 153.76,  57.76,  92.16])

In [63]:
g3 = sqdev(G3)

In [64]:
g3

array([190.44,  38.44,  17.64, 295.84, 190.44])

In [68]:
#Sum of squared deviations from the mean (SS) for the groups:
SS= [sum(g1), sum(g2),sum(g3)]

In [69]:
SS

[612.8, 515.2, 732.8]

In [75]:
f, p = stats.f_oneway(G1,G2,G3)

In [78]:
print("F stat value is:")
print(f)
print("\n")
print("p < 0.05:")
print(p)

F stat value is:
9.747205503009463


p < 0.05:
0.0030597541434430556


In [87]:
#Since P value is less than 0.05 hence Null hypothesis is rejected

In [80]:
#Problem 3:

In [81]:
#Calculate F Test for given 10, 20, 30, 40, 50 and 5,10,15, 20, 25.
#For 10, 20, 30, 40, 50:

In [82]:
D1 = [10,20,30,40,50]
D2 = [5,10,15,20,25]
D3 = [10,20,30,40,50]

In [83]:
f, p = stats.f_oneway(D1,D2,D3)

In [85]:
print("F stat value is:")
print(f)
print("\n")
print("p > 0.05:")
print(p)

F stat value is:
2.0


p > 0.05:
0.177978515625


In [86]:
#Since P value is greater than 0.05 hence we fail to reject Null hypothesis